#
# Makefile for the NCTUns engine module
#

obj-y	= \
	adaptation_field_data_descriptor.o \
	contention_control_descriptor.o \
	correction_message_descriptor.o \
	data_broadcast_id_descriptor.o \
	descriptor.o \
	descriptor_q.o \
	ip_mac_platform_name_descriptor.o \
	ip_mac_platform_provider_name_descriptor.o \
	ip_mac_stream_location_descriptor.o \
	linkage_descriptor.o \
	logon_initialize_descriptor.o \
	network_name_descriptor.o \
	rcs_content_descriptor.o \
	satellite_delivery_system_descriptor.o \
	service_move_descriptor.o \
	stream_identifier_descriptor.o \
	sync_assign_descriptor.o \
	table_update_descriptor.o \
	target_ip_slash_descriptor.o \
	target_mac_address_descriptor.o
