#
# Makefile for the NCTUns engine module
#

obj-y    = \
    mac802_16j_pmpbs.o \
    mac802_16j_pmpms.o \
    scheduler.o \
    ms_base.o \
    msobject.o \
    rs_base.o \
    mac802_16j_pmprs.o \
    rsobject.o
