#
# Makefile for the NCTUns engine module
#

obj-y    = \
    connection.o \
    library.o \
    mac802_16e.o \
    mac_address.o \
    management_message.o \
    service_flow.o \
    timer_mngr.o \
    ofdma_map_ie.o \
    neighbor_bs.o

obj-y    += \
    pmp/
