#
# Makefile for the NCTUns engine module
#

obj-y    = \
    ofdma_channel_coding_NT.o \
    ofdma_channel_model_NT.o \
    ofdma_80216j_NT.o \
    ofdma_pmpbs_NT.o \
    ofdma_pmpms_NT.o \
    ofdma_pmprs_NT.o

obj-y    += fec/
