#
# Makefile for the NCTUns engine module
#

obj-y	= \
	dvb_pkt.o \
	dvbrcs_api.o \
	dvb_s2_pls.o \
	sac.o \
	rcst_info.o \
	ncc_config.o \
	parse_ncc_config.o \
	delay.o\
	pcr.o

obj-y	+= \
	descriptor/ \
	errormodel/ \
	fec/ \
	table/
