#
# Makefile for the NCTUns engine module
#

obj-y    = \
    ofdma_channel_coding_MR.o \
    ofdma_channel_model_MR.o \
    ofdma_80216j.o \
    ofdma_pmpbs_MR.o \
    ofdma_pmpms_MR.o \
    ofdma_pmprs_MR.o

obj-y    += fec/
