#
# Makefile for the NCTUns engine module
#

obj-y	= \
	emb_data_hdr.o \
	emb_ie_network_des.o \
	emb_ie_net_entry_open.o \
	emb_ie_net_entry_ack.o \
	emb_ie_link_est.o

CXXFLAGS_emb_ie_net_entry_open.o:=-Wno-deprecated
CXXFLAGS_emb_ie_link_est.o:=-Wno-deprecated
CXXFLAGS_emb_ie_net_entry_ack.o:=-Wno-deprecated
