#
# Makefile for the NCTUns engine module
#

obj-y	= \
	dgm_section.o \
	fct_section.o \
	fct_table.o \
	fct_table_q.o \
	int_section.o \
	int_table.o \
	int_table_q.o \
	nit_section.o \
	nit_table.o \
	nit_table_q.o \
	pat_section.o \
	pat_table.o \
	pat_table_q.o \
	pmt_section.o \
	pmt_table.o \
	pmt_table_q.o \
	sct_section.o \
	sct_table.o \
	sct_table_q.o \
	section_draft.o \
	table.o \
	tbtp_section.o \
	tbtp_table.o \
	tbtp_table_list.o \
	tbtp_table_q.o \
	tct_section.o \
	tct_table.o \
	tct_table_q.o \
	tim_section.o \
	tim_table.o
