#
# Makefile for the NCTUns engine module
#

obj-y	= \
	dvb_rcs.o \
	dvb_rcs_gw.o \
	dvb_rcs_rcst.o \
	rcs_atm.o \
	rcs_atm_rcst.o \
	rcs_atm_sp.o \
	rcs_mac.o \
	rcs_mac_rcst.o \
	rcs_mac_spncc.o

obj-y	+= queue/
