#
# Makefile for the NCTUns engine module
#

obj-y	= \
	power/ \
	awphy.o \
	phy.o \
	wphy.o \
	cm.o
obj-y	+= 80211a_phy/

lib-name := libawp.so

lib-y	= \
	modulation/BPSK.o \
	modulation/CCK.o \
	modulation/GMSK.o \
	modulation/modulation.o \

clean-files := libawp.so
