#
# Makefile for the NCTUns engine module
#

obj-y	= \
	dvb_s2.o \
	dvb_s2_fec.o \
	dvb_s2_feeder.o \
	dvb_s2_ldpc.o \
	dvb_s2_rcst.o \
	mpe.o \
	mpeg2_ts_ncc.o \
	mpeg2_ts_rcst.o \
	mpeg2_ts_sp.o \
	section.o
