#
# Makefile for the NCTUns engine module
#

obj-y    = \
    mac802_16j_NT_pmpbs.o \
    mac802_16j_NT_pmpms.o \
    mac802_16j_NT_pmprs.o \
    cross802_16j_NT_pmprs.o \
    scheduler.o \
    ms_base_NT.o \
    rs_base_NT.o \
    msobject_NT.o \
    rsobject_NT.o
