#
# Makefile for the NCTUns engine module
#

obj-y	= \
	rcst_queue_manager.o \
	rcst_queue_basic.o \
	rcst_queue_ctrl.o \
	rcst_queue_rt.o \
	rcst_queue_vrrt.o \
	rcst_queue_vrjt.o \
	rcst_queue_jt.o
