TARGET := Magent1 Magent2 Magent3 Magent4 Magent5-c Magent5-t
TARGET += CarAgent CarAgent_Down CarAgent_Broken CarAgent_LaneSwitch CarAgent_SlowDown SignalAgent1 RSUAgent WSM WSM_Forwarding 
SHARE_OBJS := AStar.o map.o sock_skel.o tactic_api.o auto_vehicle_signal.o road.o 

CXXLINK := 1

include ../../scripts/Makefile.tools

