
all: test_80211e_association_request_framebody test_80211e_association_response_framebody test_80211e_authentication_framebody test_80211e_deauthentication_framebody test_80211e_beacon_framebody test_80211e_disassociation_framebody test_80211e_probe_request_framebody test_80211e_probe_response_framebody test_80211e_reassociation_request_framebody test_80211e_reassociation_response_framebody test_80211e_ADDTS_request_framebody test_80211e_ADDTS_response_framebody test_80211e_DELTS_framebody test_80211e_schedule_framebody test_80211e_DLS_request_framebody test_80211e_DLS_response_framebody test_80211e_DLS_teardown_framebody test_80211e_ADDBA_request_framebody test_80211e_ADDBA_response_framebody test_80211e_DELBA_framebody 

test_80211e_association_request_framebody: mac-802_11e_management_framebody.o test_80211e_association_request_framebody.o
	g++ -Wall -g -o test_80211e_association_request_framebody mac-802_11e_management_framebody.o test_80211e_association_request_framebody.o 

test_80211e_association_response_framebody: mac-802_11e_management_framebody.o test_80211e_association_response_framebody.o
	g++ -Wall -g -o test_80211e_association_response_framebody mac-802_11e_management_framebody.o test_80211e_association_response_framebody.o 

test_80211e_authentication_framebody: mac-802_11e_management_framebody.o test_80211e_authentication_framebody.o 
	g++ -Wall -g -o test_80211e_authentication_framebody mac-802_11e_management_framebody.o test_80211e_authentication_framebody.o 

test_80211e_deauthentication_framebody: mac-802_11e_management_framebody.o test_80211e_deauthentication_framebody.o 
	g++ -Wall -g -o test_80211e_deauthentication_framebody mac-802_11e_management_framebody.o test_80211e_deauthentication_framebody.o 

test_80211e_beacon_framebody: mac-802_11e_management_framebody.o test_80211e_beacon_framebody.o 
	g++ -Wall -g -o test_80211e_beacon_framebody mac-802_11e_management_framebody.o test_80211e_beacon_framebody.o 

test_80211e_disassociation_framebody: mac-802_11e_management_framebody.o test_80211e_disassociation_framebody.o 
	g++ -Wall -g -o test_80211e_disassociation_framebody  mac-802_11e_management_framebody.o test_80211e_disassociation_framebody.o 

test_80211e_probe_request_framebody: mac-802_11e_management_framebody.o test_80211e_probe_request_framebody.o 
	g++ -Wall -g -o test_80211e_probe_request_framebody mac-802_11e_management_framebody.o test_80211e_probe_request_framebody.o 

test_80211e_probe_response_framebody: mac-802_11e_management_framebody.o test_80211e_probe_response_framebody.o 
	g++ -Wall -g -o test_80211e_probe_response_framebody mac-802_11e_management_framebody.o test_80211e_probe_response_framebody.o 

test_80211e_reassociation_request_framebody: mac-802_11e_management_framebody.o test_80211e_reassociation_request_framebody.o 
	g++ -Wall -g -o test_80211e_reassociation_request_framebody mac-802_11e_management_framebody.o test_80211e_reassociation_request_framebody.o 

test_80211e_reassociation_response_framebody: mac-802_11e_management_framebody.o test_80211e_reassociation_response_framebody.o 
	g++ -Wall -g -o test_80211e_reassociation_response_framebody mac-802_11e_management_framebody.o test_80211e_reassociation_response_framebody.o 

test_80211e_ADDTS_request_framebody: mac-802_11e_management_framebody.o test_80211e_ADDTS_request_framebody.o
	g++ -Wall -g -o test_80211e_ADDTS_request_framebody mac-802_11e_management_framebody.o test_80211e_ADDTS_request_framebody.o 

test_80211e_ADDTS_response_framebody: mac-802_11e_management_framebody.o test_80211e_ADDTS_response_framebody.o
	g++ -Wall -g -o test_80211e_ADDTS_response_framebody mac-802_11e_management_framebody.o test_80211e_ADDTS_response_framebody.o 

test_80211e_DELTS_framebody: mac-802_11e_management_framebody.o test_80211e_DELTS_framebody.o
	g++ -Wall -g -o test_80211e_DELTS_framebody mac-802_11e_management_framebody.o test_80211e_DELTS_framebody.o 

test_80211e_schedule_framebody: mac-802_11e_management_framebody.o test_80211e_schedule_framebody.o
	g++ -Wall -g -o test_80211e_schedule_framebody mac-802_11e_management_framebody.o test_80211e_schedule_framebody.o 

test_80211e_DLS_request_framebody: mac-802_11e_management_framebody.o test_80211e_DLS_request_framebody.o
	g++ -Wall -g -o test_80211e_DLS_request_framebody mac-802_11e_management_framebody.o test_80211e_DLS_request_framebody.o 

test_80211e_DLS_response_framebody: mac-802_11e_management_framebody.o test_80211e_DLS_response_framebody.o
	g++ -Wall -g -o test_80211e_DLS_response_framebody mac-802_11e_management_framebody.o test_80211e_DLS_response_framebody.o 

test_80211e_DLS_teardown_framebody: mac-802_11e_management_framebody.o test_80211e_DLS_teardown_framebody.o
	g++ -Wall -g -o test_80211e_DLS_teardown_framebody mac-802_11e_management_framebody.o test_80211e_DLS_teardown_framebody.o 

test_80211e_ADDBA_request_framebody: mac-802_11e_management_framebody.o test_80211e_ADDBA_request_framebody.o
	g++ -Wall -g -o test_80211e_ADDBA_request_framebody mac-802_11e_management_framebody.o test_80211e_ADDBA_request_framebody.o 

test_80211e_ADDBA_response_framebody: mac-802_11e_management_framebody.o test_80211e_ADDBA_response_framebody.o
	g++ -Wall -g -o test_80211e_ADDBA_response_framebody mac-802_11e_management_framebody.o test_80211e_ADDBA_response_framebody.o 

test_80211e_DELBA_framebody: mac-802_11e_management_framebody.o test_80211e_DELBA_framebody.o
	g++ -Wall -g -o test_80211e_DELBA_framebody mac-802_11e_management_framebody.o test_80211e_DELBA_framebody.o 


mac-802_11e_management_framebody.o: ../mac-802_11e_management_framebody.h ../mac-802_11e_management_framebody.cc
	g++ -Wall -g -c -o mac-802_11e_management_framebody.o ../mac-802_11e_management_framebody.cc

test_80211e_association_request_framebody.o: ../mac-802_11e_management_framebody.h test_80211e_association_request_framebody.c
	g++ -Wall -g -c -o test_80211e_association_request_framebody.o test_80211e_association_request_framebody.c

test_80211e_association_response_framebody.o: ../mac-802_11e_management_framebody.h test_80211e_association_response_framebody.c
	g++ -Wall -g -c -o test_80211e_association_response_framebody.o test_80211e_association_response_framebody.c

test_80211e_authentication_framebody.o: ../mac-802_11e_management_framebody.h test_80211e_authentication_framebody.c
	g++ -Wall -g -c -o test_80211e_authentication_framebody.o test_80211e_authentication_framebody.c

test_80211e_deauthentication_framebody.o: ../mac-802_11e_management_framebody.h test_80211e_deauthentication_framebody.c
	g++ -Wall -g -c -o test_80211e_deauthentication_framebody.o test_80211e_deauthentication_framebody.c

test_80211e_beacon_framebody.o: ../mac-802_11e_management_framebody.h test_80211e_beacon_framebody.c
	g++ -Wall -g -c -o test_80211e_beacon_framebody.o test_80211e_beacon_framebody.c

test_80211e_disassociation_framebody.o: ../mac-802_11e_management_framebody.h test_80211e_disassociation_framebody.c
	g++ -Wall -g -c -o test_80211e_disassociation_framebody.o test_80211e_disassociation_framebody.c

test_80211e_probe_request_framebody.o: ../mac-802_11e_management_framebody.h test_80211e_probe_request_framebody.c
	g++ -Wall -g -c -o test_80211e_probe_request_framebody.o test_80211e_probe_request_framebody.c

test_80211e_probe_response_framebody.o: ../mac-802_11e_management_framebody.h test_80211e_probe_response_framebody.c
	g++ -Wall -g -c -o test_80211e_probe_response_framebody.o test_80211e_probe_response_framebody.c

test_80211e_reassociation_request_framebody.o: ../mac-802_11e_management_framebody.h test_80211e_reassociation_request_framebody.c
	g++ -Wall -g -c -o test_80211e_reassociation_request_framebody.o test_80211e_reassociation_request_framebody.c

test_80211e_reassociation_response_framebody.o: ../mac-802_11e_management_framebody.h test_80211e_reassociation_response_framebody.c
	g++ -Wall -g -c -o test_80211e_reassociation_response_framebody.o test_80211e_reassociation_response_framebody.c

test_80211e_ADDTS_request_framebody.o: ../mac-802_11e_management_framebody.h test_80211e_ADDTS_request_framebody.c
	g++ -Wall -g -c -o test_80211e_ADDTS_request_framebody.o test_80211e_ADDTS_request_framebody.c

test_80211e_ADDTS_response_framebody.o: ../mac-802_11e_management_framebody.h test_80211e_ADDTS_response_framebody.c
	g++ -Wall -g -c -o test_80211e_ADDTS_response_framebody.o test_80211e_ADDTS_response_framebody.c

test_80211e_DELTS_framebody.o: ../mac-802_11e_management_framebody.h test_80211e_DELTS_framebody.c
	g++ -Wall -g -c -o test_80211e_DELTS_framebody.o test_80211e_DELTS_framebody.c

test_80211e_schedule_framebody.o: ../mac-802_11e_management_framebody.h test_80211e_schedule_framebody.c
	g++ -Wall -g -c -o test_80211e_schedule_framebody.o test_80211e_schedule_framebody.c

test_80211e_DLS_request_framebody.o: ../mac-802_11e_management_framebody.h test_80211e_DLS_request_framebody.c
	g++ -Wall -g -c -o test_80211e_DLS_request_framebody.o test_80211e_DLS_request_framebody.c

test_80211e_DLS_response_framebody.o: ../mac-802_11e_management_framebody.h test_80211e_DLS_response_framebody.c
	g++ -Wall -g -c -o test_80211e_DLS_response_framebody.o test_80211e_DLS_response_framebody.c

test_80211e_DLS_teardown_framebody.o: ../mac-802_11e_management_framebody.h test_80211e_DLS_teardown_framebody.c
	g++ -Wall -g -c -o test_80211e_DLS_teardown_framebody.o test_80211e_DLS_teardown_framebody.c

test_80211e_ADDBA_request_framebody.o: ../mac-802_11e_management_framebody.h test_80211e_ADDBA_request_framebody.c
	g++ -Wall -g -c -o test_80211e_ADDBA_request_framebody.o test_80211e_ADDBA_request_framebody.c

test_80211e_ADDBA_response_framebody.o: ../mac-802_11e_management_framebody.h test_80211e_ADDBA_response_framebody.c
	g++ -Wall -g -c -o test_80211e_ADDBA_response_framebody.o test_80211e_ADDBA_response_framebody.c

test_80211e_DELBA_framebody.o: ../mac-802_11e_management_framebody.h test_80211e_DELBA_framebody.c
	g++ -Wall -g -c -o test_80211e_DELBA_framebody.o test_80211e_DELBA_framebody.c

clean:
	rm -f *.o test_80211e_association_request_framebody test_80211e_association_response_framebody test_80211e_authentication_framebody test_80211e_deauthentication_framebody test_80211e_beacon_framebody test_80211e_disassociation_framebody test_80211e_probe_request_framebody test_80211e_probe_response_framebody test_80211e_reassociation_request_framebody test_80211e_reassociation_response_framebody test_80211e_ADDTS_request_framebody test_80211e_ADDTS_response_framebody test_80211e_DELTS_framebody test_80211e_schedule_framebody test_80211e_DLS_request_framebody test_80211e_DLS_response_framebody test_80211e_DLS_teardown_framebody test_80211e_ADDBA_request_framebody test_80211e_ADDBA_response_framebody test_80211e_DELBA_framebody 

